

-- 용자의땅 오픈소스에서 가져옴
-- from MSF Braver's Land
-- Thanks to DemonLanterns, -Men-
function Install_DemBoss()-- This text is generated by TrigEditPlus

	local CX = CreateVar()
	local CY = CreateVar()

	CIfX(FP,Bring(FP,AtLeast,1,"Terran Civilian",64),SetCVar(FP,VResetSw3[2],SetTo,0))
	CIf(FP,{NTCond()},{SetMemory(0x66FABC, SetTo, 365),SetMemory(0x6509B0,SetTo,FP)})--다크아칸 에너지 스크립트 복구
	DoActions(FP,{
		SetAllianceStatus(P11, Ally);
		SetAllianceStatus(P10, Ally);
		SetAllianceStatus(P9, Ally);
		SetAllianceStatus(P12, Ally);
	})

	Trigger2(FP,{Void(4,AtMost,0)},{
		SetVoid(4,SetTo,1),
	},{Preserved})
	MoveMarineArr2 = {}
	for i = 0, 6 do
	table.insert(MoveMarineArr2,MoveUnit(All,"Men",i,"Create 1",2+i))
	table.insert(MoveMarineArr2,MoveUnit(All,"Men",i,"Create 2",2+i))
	for j = 0, 4 do
	table.insert(MoveMarineArr2,MoveUnit(All,"Men",i,"Create 1",20+j))
	table.insert(MoveMarineArr2,MoveUnit(All,"Men",i,"Create 2",20+j))
	end
	end
	DoActions2(FP,MoveMarineArr2)

	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			MoveLocation("Last Boss 93", "Terran Civilian", P8, "Anywhere");
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
		},
		actions = {
			PreserveTrigger();
			Order("Terran Civilian", P8, "Anywhere", Move, "Last Boss 93");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(AllPlayers, Exactly, 0, "Terran Wraith", "Anywhere");
			Bring(AllPlayers, Exactly, 0, "Tom Kazansky (Wraith)", "Anywhere");
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 0); 
			Void(1, Exactly, 0);
		},
		actions = {
			PreserveTrigger();
			SetVoid(0, SetTo, 1); 
			SetVoid(1, SetTo, 1);
			SetVoid(2, SetTo, 1);
			MoveLocation("C1", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C2", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C3", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C4", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C5", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C6", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C7", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C8", "Terran Civilian", P8, "Anywhere");
			MoveLocation("BattlecruiserHome 23", "Terran Civilian", P8, "Anywhere");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 4); 
			Void(1, Exactly, 0);
		},
		actions = {
			PreserveTrigger();
			SetVoid(0, SetTo, 4); 
			SetVoid(1, SetTo, 1);
			SetVoid(2, SetTo, 1);
			MoveLocation("C1", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C2", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C3", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C4", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C5", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C6", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C7", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C8", "Terran Civilian", P8, "Anywhere");
			MoveLocation("BattlecruiserHome 23", "Terran Civilian", P8, "Anywhere");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 1); 
			Void(2, AtLeast, 1);
			Void(2, AtMost, 23);
		},
		actions = {
			PreserveTrigger();
			CreateUnit(1, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C1");
			MoveLocation("C1", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(2, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C2");
			MoveLocation("C2", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(3, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C3");
			MoveLocation("C3", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(4, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C4");
			MoveLocation("C4", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(5, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C5");
			MoveLocation("C5", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(6, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C6");
			MoveLocation("C6", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(7, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C7");
			MoveLocation("C7", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(8, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C8");
			MoveLocation("C8", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 4); 
			Void(2, AtLeast, 1);
			Void(2, AtMost, 11);
		},
		actions = {
			PreserveTrigger();
			CreateUnit(1, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C1");
			MoveLocation("C1", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(2, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C2");
			MoveLocation("C2", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(3, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C3");
			MoveLocation("C3", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(4, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C4");
			MoveLocation("C4", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(5, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C5");
			MoveLocation("C5", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(6, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C6");
			MoveLocation("C6", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(7, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C7");
			MoveLocation("C7", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(8, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C8");
			MoveLocation("C8", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 1); 
			Void(2, AtLeast, 1);
			Void(2, AtMost, 23);
		},
		actions = {
			PreserveTrigger();
			CreateUnit(8, "Protoss Dark Archon", "Create 1", P8);
			CreateUnit(8, "Kakaru (Twilight)", "Create 1", P8);
			CreateUnitWithProperties(8, "Protoss Dragoon", "Create 1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(8, "Fenix (Zealot)", "Create 1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = false,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C1");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C2");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C3");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C4");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C5");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C6");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C7");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C8");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C1");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C2");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C3");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C4");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C5");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C6");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C7");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C8");
			MoveUnit(1, "Protoss Dragoon", P8, "Create", "C1");
			MoveUnit(1, "Protoss Dragoon", P8, "Create", "C2");
			MoveUnit(1, "Protoss Dragoon", P8, "Create", "C3");
			MoveUnit(1, "Protoss Dragoon", P8, "Create", "C4");
			MoveUnit(1, "Protoss Dragoon", P8, "Create", "C5");
			MoveUnit(1, "Protoss Dragoon", P8, "Create", "C6");
			MoveUnit(1, "Protoss Dragoon", P8, "Create", "C7");
			MoveUnit(1, "Protoss Dragoon", P8, "Create", "C8");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C8");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C7");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C6");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C5");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C4");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C3");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C2");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C1");
			killUnitAt(All,"Men","C8",Force1);
			killUnitAt(All,"Men","C7",Force1);
			killUnitAt(All,"Men","C6",Force1);
			killUnitAt(All,"Men","C5",Force1);
			killUnitAt(All,"Men","C4",Force1);
			killUnitAt(All,"Men","C3",Force1);
			killUnitAt(All,"Men","C2",Force1);
			killUnitAt(All,"Men","C1",Force1);
			RemoveUnitAt(All, "Men", "Create", P8);
			KillUnit("Protoss Dark Archon", P8);
			KillUnit("Kakaru (Twilight)", P8);
			KillUnit("Protoss Dragoon", P8);
			SetVoid(2, Add, 1);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 4); 
			Void(2, AtLeast, 1);
			Void(2, AtMost, 11);
		},
		actions = {
			PreserveTrigger();
			CreateUnit(8, "Protoss Dark Archon", "Create 1", P8);
			CreateUnit(8, "Zerg Scourge", "Create 1", P8);
			CreateUnitWithProperties(8, "Zerg Lurker", "Create 1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(8, "Zeratul (Dark Templar)", "Create 1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = false,
				hitpoint = 10,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C1");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C2");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C3");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C4");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C5");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C6");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C7");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C8");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C1");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C2");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C3");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C4");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C5");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C6");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C7");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C8");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C1");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C2");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C3");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C4");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C5");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C6");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C7");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C8");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C8");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C7");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C6");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C5");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C4");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C3");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C2");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C1");
			RemoveUnitAt(All, "Men", "Create", P8);
			KillUnit("Protoss Dark Archon", P8);
			KillUnit("Zerg Scourge", P8);
			KillUnit("Zerg Lurker", P8);
			SetVoid(2, Add, 1);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 1); 
			Void(2, AtLeast, 1);
			Void(2, Exactly, 24);
		},
		actions = {
			PreserveTrigger();
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C2", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C3", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C4", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C5", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C6", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C7", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C8", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			Order("Fenix (Zealot)", P8, "Anywhere", Patrol, "Last Boss 93");
			Wait(5000);
			KillUnit("Fenix (Zealot)", P8);
			KillUnit("Devouring One (Zergling)", P8);
			KillUnit("Hunter Killer (Hydralisk)", P8);
			SetVoid(1, SetTo, 0);
			SetVoid(2, SetTo, 0);
			SetVoid(0, SetTo, 2); 
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 4); 
			Void(2, AtLeast, 1);
			Void(2, Exactly, 12);
		},
		actions = {
			PreserveTrigger();
			CreateUnitWithProperties(1, "Terran Wraith", "C1", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Terran Wraith", P8, "C1", P9);
			CreateUnitWithProperties(1, "Terran Wraith", "C2", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Terran Wraith", P8, "C2", P10);
			CreateUnitWithProperties(1, "Terran Wraith", "C3", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Terran Wraith", P8, "C3", P11);
			CreateUnitWithProperties(1, "Terran Wraith", "C4", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Terran Wraith", P8, "C4", P12);
			CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C5", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Tom Kazansky (Wraith)", P8, "C5", P9);
			CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C6", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Tom Kazansky (Wraith)", P8, "C6", P10);
			CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C7", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Tom Kazansky (Wraith)", P8, "C7", P11);
			CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C8", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Tom Kazansky (Wraith)", P8, "C8", P12);
			Order("Zeratul (Dark Templar)", P8, "Anywhere", Patrol, "Last Boss 93");
			Wait(5000);
			SetVoid(1, SetTo, 0);
			SetVoid(2, SetTo, 0);
			SetVoid(0, SetTo, 0); 
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
		},
		actions = {
			PreserveTrigger();
			MoveLocation("C1", "Terran Wraith", P9, "Anywhere");
			MoveLocation("C2", "Terran Wraith", P10, "Anywhere");
			MoveLocation("C3", "Terran Wraith", P11, "Anywhere");
			MoveLocation("C4", "Terran Wraith", P12, "Anywhere");
			MoveLocation("C5", "Tom Kazansky (Wraith)", P9, "Anywhere");
			MoveLocation("C6", "Tom Kazansky (Wraith)", P10, "Anywhere");
			MoveLocation("C7", "Tom Kazansky (Wraith)", P11, "Anywhere");
			MoveLocation("C8", "Tom Kazansky (Wraith)", P12, "Anywhere");
			Order("Terran Wraith", P9, "Anywhere", Move, "C2");
			Order("Terran Wraith", P10, "Anywhere", Move, "C3");
			Order("Terran Wraith", P11, "Anywhere", Move, "C4");
			Order("Terran Wraith", P12, "Anywhere", Move, "C5");
			Order("Tom Kazansky (Wraith)", P9, "Anywhere", Move, "C6");
			Order("Tom Kazansky (Wraith)", P10, "Anywhere", Move, "C7");
			Order("Tom Kazansky (Wraith)", P11, "Anywhere", Move, "C8");
			Order("Tom Kazansky (Wraith)", P12, "Anywhere", Move, "C1");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
			Bring(AllPlayers, AtLeast, 4, "Tom Kazansky (Wraith)", "C1");
			Bring(AllPlayers, AtLeast, 4, "Terran Wraith", "C1");
		},
		actions = {
			PreserveTrigger();
			RemoveUnit("Terran Wraith", AllPlayers);
			RemoveUnit("Tom Kazansky (Wraith)", AllPlayers);
			RemoveUnit("Protoss Arbiter", P8);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Void(0, Exactly, 2); 
			Void(2, Exactly, 0);
		},
		actions = {
			PreserveTrigger();
			Order("Terran Civilian", P8, "Anywhere", Move, "Last Boss 93");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Void(0, Exactly, 2); 
			Void(2, AtMost, 9);
		},
		actions = {
			PreserveTrigger();
			KillUnit("Devouring One (Zergling)", P8);
			KillUnit("Hunter Killer (Hydralisk)", P8);
			KillUnit("Torrasque (Ultralisk)", P8);
			CreateUnit(9,91, "Last Boss 93", P8);
			KillUnit(91, P8);
			SetVoid(2, Add, 1);
			Wait(1000);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Void(0, Exactly, 2); 
			Void(2, AtMost, 9);
		},
		actions = {
			PreserveTrigger();
			ModifyUnitHitPoints(All, "Men", Force1, "Anywhere", 1);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P11, AtLeast, 1, "Identity JinjinZZara Noodles");
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			PreserveTrigger();
			Order("Identity JinjinZZara Noodles", P11, "Anywhere", Move, "Last Boss 93");
			SetInvincibility(Enable, "Identity JinjinZZara Noodles", P11, "Anywhere");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Identity JinjinZZara Noodles");
			Void(0, Exactly, 3); 
		},
		actions = {
			PreserveTrigger();
			SetVoid(2, Add, 1);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Identity JinjinZZara Noodles");
			Void(0, Exactly, 3); 
			Void(2, Exactly, 110);
		},
		actions = {
			PreserveTrigger();
			Order("Identity JinjinZZara Noodles", P8, "Anywhere", Patrol, "Last Boss 93");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Identity JinjinZZara Noodles");
			Void(0, Exactly, 3); 
			Void(2, AtLeast, 140);
		},
		actions = {
			PreserveTrigger();
			SetVoid(2, SetTo, 0);
			SetVoid(0, SetTo, 4); 
			SetVoid(1, SetTo, 0);
			KillUnit("Identity JinjinZZara Noodles", P8);
		},
	}
	CIf(FP,{
		Command(P11, AtMost, 149, "Identity JinjinZZara Noodles");
		Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
		Void(1, Exactly, 0);
		Void(0, Exactly, 2); 
		Void(2, AtLeast, 1);
		Void(2, AtLeast, 10);
		Memory(0x628438,AtLeast,1)
	})
		f_Read(FP,0x628438,nil,Sh_Para,0xFFFFFF)
		CDoActions(FP,{
				CreateUnitWithProperties(1, 60, "Last Boss 93", P8, {invincible = true}),
				TSetDeathsX(_Add(Sh_Para,72),SetTo,0xFF*256,0,0xFF00),
				GiveUnits(All,60,P8,64,P11),
			})
	CIfEnd()
	Trigger {
		players = {P8},
		conditions = {
			Command(P11, AtLeast, 150, "Identity JinjinZZara Noodles");
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(1, Exactly, 0);
			Void(0, Exactly, 2); 
			Void(2, AtLeast, 1);
			Void(2, AtLeast, 10);
		},
		actions = {
			PreserveTrigger();
			SetVoid(0, SetTo, 3); 
			GiveUnits(All, "Identity JinjinZZara Noodles", P11, "Anywhere", P8);
			RunAIScriptAt("Set Unit Order To: Junk Yard Dog", "Last Boss 93");
		},
	}
	
	
	-- -----구분선-----
	-- 
	-- 
	-- 
	-- 
	-- 
	
	Trigger {
		players = {P8},
		conditions = {
			Always();
		},
		actions = {
			Comment("-----구분선-----\r\n\r\n\r\n\r\n\r\n");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
			Void(1, Exactly, 0);
		},
		actions = {
			CreateUnit(1, "Kakaru (Twilight)", "Create 1", P8);
			MoveUnit(1, "Kakaru (Twilight)", P8, "Anywhere", "Last Boss 93");
			RemoveUnit("Kakaru (Twilight)", P8);
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
			Void(1, AtLeast, 1);
			Void(2, AtLeast, 11);
		},
		actions = {
			CreateUnit(1, "Kakaru (Twilight)", "Create 1", P8);
			MoveUnit(1, "Kakaru (Twilight)", P8, "Anywhere", "Last Boss 93");
			RemoveUnit("Kakaru (Twilight)", P8);
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Gantrithor (Carrier)");
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			MoveLocation("Battlecruiser4", "Gantrithor (Carrier)", P8, "Anywhere");
			MoveLocation("Battlecruiser5give", "Gantrithor (Carrier)", P8, "Anywhere");
			CreateUnit(12, "Protoss Scout", "Battlecruiser4", P8);
			MoveUnit(All, "Protoss Scout", P8, "Anywhere", "Battlecruiser4");
			KillUnit("Protoss Scout", P8);
			GiveUnits(1, "Gantrithor (Carrier)", P8, "Battlecruiser5give", P11);
			KillUnitAt(All,"Men","Battlecruiser4",Force1);
			KillUnitAt(All,"Terran Bunker","Battlecruiser4",Force1);
			KillUnitAt(All,"Terran Missile Turret","Battlecruiser4",Force1);
			PreserveTrigger();
		},
	}
	
	
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, Exactly, 0, "Gantrithor (Carrier)");
			Command(P11, AtLeast, 1, "Gantrithor (Carrier)");
		},
		actions = {
			GiveUnits(All, "Gantrithor (Carrier)", P11, "Anywhere", P8);
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			PreserveTrigger();
			Order("Gantrithor (Carrier)", P8, "Anywhere", Move, "BattlecruiserHome 23");
			Order("Gantrithor (Carrier)", P11, "Anywhere", Move, "BattlecruiserHome 23");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Gantrithor (Carrier)", "BattlecruiserHome 23");
		},
		actions = {
			KillUnitAt(1, "Gantrithor (Carrier)", "BattlecruiserHome 23", P8);
			CreateUnit(8, "Rhynadon (Badlands)", "Last Boss 93", P8);
			KillUnit("Rhynadon (Badlands)", P8);
			CreateUnitWithProperties(6, "Devouring One (Zergling)", "Last Boss 93", P8, {
				clocked = false,
				burrowed = true,
				intransit = false,
				hallucinated = false,
				invincible = false,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(3, "Hunter Killer (Hydralisk)", "Last Boss 93", P8, {
				clocked = false,
				burrowed = true,
				intransit = false,
				hallucinated = false,
				invincible = false,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnit(1, "Torrasque (Ultralisk)", "Last Boss 93", P8);
			Order("Men", P8, "Last Boss 93", Attack, "Anywhere");
			RunAIScriptAt("Set Unit Order To: Junk Yard Dog", "Last Boss 93");
			PreserveTrigger();
		},
	}
	
	
	
	
	
	-- -----구분선-----
	-- 
	-- 
	-- 
	-- 
	-- 
	
	Trigger {
		players = {P8},
		conditions = {
			Always();
		},
		actions = {
			Comment("-----구분선-----\r\n\r\n\r\n\r\n\r\n");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Void(3, Exactly, 300);
		},
		actions = {
			MoveLocation("bossLocationboss 5", "Terran Civilian", P8, "Anywhere");
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
			Bring(P8, Exactly, 0, "Terran Civilian", "bossLocationboss 5");
			Void(3, AtLeast, 600);
		},
		actions = {
			CreateUnit(1, "Edmund Duke (Siege Mode)", "Last Boss 93", P8);
			CreateUnit(1, "Edmund Duke (Siege Mode)", "bossLocationboss 5", P8);
			CreateUnit(9, "Tassadar/Zeratul (Archon)", "Last Boss 93", P8);
			KillUnit("Tassadar/Zeratul (Archon)", P8);
			MoveUnit(All, "Terran Civilian", P8, "Anywhere", "bossLocationboss 5");
			SetVoid(3, SetTo, 0);
			MoveLocation("bossLocationboss 5", "Terran Civilian", P8, "Anywhere");
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
			Bring(P8, Exactly, 1, "Terran Civilian", "bossLocationboss 5");
			Void(3, AtLeast, 600);
		},
		actions = {
			CreateUnit(1, "Edmund Duke (Siege Mode)", "Last Boss 93", P8);
			CreateUnit(1, "Edmund Duke (Siege Mode)", "BattlecruiserHome 23", P8);
			CreateUnit(9, "Tassadar/Zeratul (Archon)", "Last Boss 93", P8);
			KillUnit("Tassadar/Zeratul (Archon)", P8);
			MoveUnit(All, "Terran Civilian", P8, "Anywhere", "BattlecruiserHome 23");
			SetVoid(3, SetTo, 0);
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			SetVoid(3, Add, 1);
			PreserveTrigger();
		},
	}
	
	
	GetLocCenter("Last Boss 93",CX,CY)
	f_Recall({
		Command(P11, AtMost, 149, "Identity JinjinZZara Noodles");
		Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
		Void(1, Exactly, 0);
		Void(0, Exactly, 2); 
		Void(2, AtLeast, 1);
		Void(2, AtLeast, 10);
	},CX,CY)

	CIf(FP,Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere"))
	GetLocCenter("C1",CX,CY)
	f_Recall(nil,CX,CY)
	GetLocCenter("C2",CX,CY)
	f_Recall(nil,CX,CY)
	GetLocCenter("C3",CX,CY)
	f_Recall(nil,CX,CY)
	GetLocCenter("C4",CX,CY)
	f_Recall(nil,CX,CY)
	GetLocCenter("C5",CX,CY)
	f_Recall(nil,CX,CY)
	GetLocCenter("C6",CX,CY)
	f_Recall(nil,CX,CY)
	GetLocCenter("C7",CX,CY)
	f_Recall(nil,CX,CY)
	GetLocCenter("C8",CX,CY)
	f_Recall(nil,CX,CY)
	CIfEnd()
	Trigger {
		players = {Force1},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
			Void(0, Exactly, 3); 
			Void(2, AtLeast, 138);
		},
		actions = {
			RunAIScript("Turn OFF Shared Vision for Player 8");
		},
	}
	OWTable = {}
	for i = 0, 95 do
		if i <= 20 or i >= 75 then 
	table.insert(OWTable,SetLoc("OW","L",SetTo,i*32))
	table.insert(OWTable,SetLoc("OW","R",SetTo,32+(i*32)))
	table.insert(OWTable,SetLoc("OWDest","L",SetTo,i*32))
	table.insert(OWTable,SetLoc("OWDest","R",SetTo,32+(i*32)))
	table.insert(OWTable,Order("Men",Force1,"OW",Move,"OWDest"))
		end
	end
	DoActions2(FP,OWTable)
	
	
	Trigger {
		players = {Force1},
		actions = {
			RunAIScript("Turn ON Shared Vision for Player 8");
			PreserveTrigger();
		},
	}
	CIfEnd()
	CElseIfX({CVar(FP,VResetSw3[2],Exactly,0),Bring(FP,AtMost,0,"Terran Civilian",64)},SetCVar(FP,VResetSw3[2],SetTo,1))
		DoActionsX(FP,{KillUnit(60,FP),KillUnit(60,P9),SetCDeaths(FP,Add,1,DemClear)})
		DoActions(FP,{
			SetVoid(0,SetTo,0);
			SetVoid(1,SetTo,0);
			SetVoid(2,SetTo,0);
			SetVoid(3,SetTo,0);
			SetVoid(4,SetTo,0);
		})
	CIfXEnd()
	
	
end