

-- 용자의땅 오픈소스에서 가져옴
-- Thanks to DemonLanterns, -Men-
function Install_DemBoss()-- This text is generated by TrigEditPlus

    -- -----구분선-----
    -- 
    -- 
    -- 
    -- 
    -- 
    
    Trigger {
        players = {P8},
        conditions = {
            Always();
        },
        actions = {
            Comment("-----구분선-----\r\n\r\n\r\n\r\n\r\n");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Switch("Switch 12", Set);
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
        },
        actions = {
            MoveLocation("Last Boss 93", "Terran Civilian", CurrentPlayer, "Anywhere");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
        },
        actions = {
            PreserveTrigger();
            Order("Terran Civilian", CurrentPlayer, "Anywhere", Move, "Last Boss 93");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(AllPlayers, Exactly, 0, "Terran Wraith", "Anywhere");
            Bring(AllPlayers, Exactly, 0, "Tom Kazansky (Wraith)", "Anywhere");
            Bring(CurrentPlayer, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 0, "Right Pit Door");
            Deaths(P8, Exactly, 0, "Left Pit Door");
        },
        actions = {
            PreserveTrigger();
            SetDeaths(P8, SetTo, 1, "Right Pit Door");
            SetDeaths(P8, SetTo, 1, "Left Pit Door");
            SetDeaths(P8, SetTo, 1, "Right Upper Level Door");
            MoveLocation("C1", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C2", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C3", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C4", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C5", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C6", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C7", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C8", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("BattlecruiserHome 23", "Terran Civilian", CurrentPlayer, "Anywhere");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 4, "Right Pit Door");
            Deaths(P8, Exactly, 0, "Left Pit Door");
        },
        actions = {
            PreserveTrigger();
            SetDeaths(P8, SetTo, 4, "Right Pit Door");
            SetDeaths(P8, SetTo, 1, "Left Pit Door");
            SetDeaths(P8, SetTo, 1, "Right Upper Level Door");
            MoveLocation("C1", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C2", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C3", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C4", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C5", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C6", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C7", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("C8", "Terran Civilian", CurrentPlayer, "Anywhere");
            MoveLocation("BattlecruiserHome 23", "Terran Civilian", CurrentPlayer, "Anywhere");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 1, "Right Pit Door");
            Deaths(P8, AtLeast, 1, "Right Upper Level Door");
            Deaths(P8, AtMost, 23, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            CreateUnit(1, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C1");
            MoveLocation("C1", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(2, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C2");
            MoveLocation("C2", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(3, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C3");
            MoveLocation("C3", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(4, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C4");
            MoveLocation("C4", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(5, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C5");
            MoveLocation("C5", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(6, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C6");
            MoveLocation("C6", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(7, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C7");
            MoveLocation("C7", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(8, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C8");
            MoveLocation("C8", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 4, "Right Pit Door");
            Deaths(P8, AtLeast, 1, "Right Upper Level Door");
            Deaths(P8, AtMost, 11, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            CreateUnit(1, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C1");
            MoveLocation("C1", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(2, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C2");
            MoveLocation("C2", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(3, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C3");
            MoveLocation("C3", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(4, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C4");
            MoveLocation("C4", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(5, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C5");
            MoveLocation("C5", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(6, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C6");
            MoveLocation("C6", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(7, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C7");
            MoveLocation("C7", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
            CreateUnit(8, "Zerg Devourer", "Create 1", CurrentPlayer);
            CreateUnit(1, "Danimoth (Arbiter)", "Create 2", CurrentPlayer);
            MoveUnit(All, "Men", CurrentPlayer, "Create", "C8");
            MoveLocation("C8", "Danimoth (Arbiter)", CurrentPlayer, "Anywhere");
            RemoveUnit("Danimoth (Arbiter)", CurrentPlayer);
            RemoveUnit("Zerg Devourer", CurrentPlayer);
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 1, "Right Pit Door");
            Deaths(P8, AtLeast, 1, "Right Upper Level Door");
            Deaths(P8, AtMost, 23, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            CreateUnit(8, "Protoss Dark Archon", "Create 1", CurrentPlayer);
            CreateUnit(8, "Protoss Observer", "Create 1", CurrentPlayer);
            CreateUnitWithProperties(8, "Protoss Dragoon", "Create 1", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(8, "Fenix (Zealot)", "Create 1", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = false,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Create", "C1");
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Create", "C2");
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Create", "C3");
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Create", "C4");
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Create", "C5");
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Create", "C6");
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Create", "C7");
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Create", "C8");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C1");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C2");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C3");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C4");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C5");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C6");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C7");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C8");
            MoveUnit(1, "Protoss Dragoon", CurrentPlayer, "Create", "C1");
            MoveUnit(1, "Protoss Dragoon", CurrentPlayer, "Create", "C2");
            MoveUnit(1, "Protoss Dragoon", CurrentPlayer, "Create", "C3");
            MoveUnit(1, "Protoss Dragoon", CurrentPlayer, "Create", "C4");
            MoveUnit(1, "Protoss Dragoon", CurrentPlayer, "Create", "C5");
            MoveUnit(1, "Protoss Dragoon", CurrentPlayer, "Create", "C6");
            MoveUnit(1, "Protoss Dragoon", CurrentPlayer, "Create", "C7");
            MoveUnit(1, "Protoss Dragoon", CurrentPlayer, "Create", "C8");
            MoveUnit(1, "Fenix (Zealot)", CurrentPlayer, "Create", "C8");
            MoveUnit(1, "Fenix (Zealot)", CurrentPlayer, "Create", "C7");
            MoveUnit(1, "Fenix (Zealot)", CurrentPlayer, "Create", "C6");
            MoveUnit(1, "Fenix (Zealot)", CurrentPlayer, "Create", "C5");
            MoveUnit(1, "Fenix (Zealot)", CurrentPlayer, "Create", "C4");
            MoveUnit(1, "Fenix (Zealot)", CurrentPlayer, "Create", "C3");
            MoveUnit(1, "Fenix (Zealot)", CurrentPlayer, "Create", "C2");
            MoveUnit(1, "Fenix (Zealot)", CurrentPlayer, "Create", "C1");
            MoveUnit(All, "Men", Force1, "C8", "Location 236AAA");
            MoveUnit(All, "Men", Force1, "C7", "Location 236AAA");
            MoveUnit(All, "Men", Force1, "C6", "Location 236AAA");
            MoveUnit(All, "Men", Force1, "C5", "Location 236AAA");
            MoveUnit(All, "Men", Force1, "C4", "Location 236AAA");
            MoveUnit(All, "Men", Force1, "C3", "Location 236AAA");
            MoveUnit(All, "Men", Force1, "C2", "Location 236AAA");
            MoveUnit(All, "Men", Force1, "C1", "Location 236AAA");
            RemoveUnitAt(All, "Men", "Create", CurrentPlayer);
            KillUnit("Protoss Dark Archon", CurrentPlayer);
            KillUnit("Protoss Observer", CurrentPlayer);
            KillUnit("Protoss Dragoon", CurrentPlayer);
            SetDeaths(P8, Add, 1, "Right Upper Level Door");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 4, "Right Pit Door");
            Deaths(P8, AtLeast, 1, "Right Upper Level Door");
            Deaths(P8, AtMost, 11, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            CreateUnit(8, "Protoss Dark Archon", "Create 1", CurrentPlayer);
            CreateUnit(8, "Zerg Scourge", "Create 1", CurrentPlayer);
            CreateUnitWithProperties(8, "Zerg Lurker", "Create 1", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(8, "Zeratul (Dark Templar)", "Create 1", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = false,
                hitpoint = 10,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            MoveUnit(1, "Zerg Scourge", CurrentPlayer, "Create", "C1");
            MoveUnit(1, "Zerg Scourge", CurrentPlayer, "Create", "C2");
            MoveUnit(1, "Zerg Scourge", CurrentPlayer, "Create", "C3");
            MoveUnit(1, "Zerg Scourge", CurrentPlayer, "Create", "C4");
            MoveUnit(1, "Zerg Scourge", CurrentPlayer, "Create", "C5");
            MoveUnit(1, "Zerg Scourge", CurrentPlayer, "Create", "C6");
            MoveUnit(1, "Zerg Scourge", CurrentPlayer, "Create", "C7");
            MoveUnit(1, "Zerg Scourge", CurrentPlayer, "Create", "C8");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C1");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C2");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C3");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C4");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C5");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C6");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C7");
            MoveUnit(1, "Protoss Dark Archon", CurrentPlayer, "Create", "C8");
            MoveUnit(1, "Zerg Lurker", CurrentPlayer, "Create", "C1");
            MoveUnit(1, "Zerg Lurker", CurrentPlayer, "Create", "C2");
            MoveUnit(1, "Zerg Lurker", CurrentPlayer, "Create", "C3");
            MoveUnit(1, "Zerg Lurker", CurrentPlayer, "Create", "C4");
            MoveUnit(1, "Zerg Lurker", CurrentPlayer, "Create", "C5");
            MoveUnit(1, "Zerg Lurker", CurrentPlayer, "Create", "C6");
            MoveUnit(1, "Zerg Lurker", CurrentPlayer, "Create", "C7");
            MoveUnit(1, "Zerg Lurker", CurrentPlayer, "Create", "C8");
            MoveUnit(1, "Zeratul (Dark Templar)", CurrentPlayer, "Create", "C8");
            MoveUnit(1, "Zeratul (Dark Templar)", CurrentPlayer, "Create", "C7");
            MoveUnit(1, "Zeratul (Dark Templar)", CurrentPlayer, "Create", "C6");
            MoveUnit(1, "Zeratul (Dark Templar)", CurrentPlayer, "Create", "C5");
            MoveUnit(1, "Zeratul (Dark Templar)", CurrentPlayer, "Create", "C4");
            MoveUnit(1, "Zeratul (Dark Templar)", CurrentPlayer, "Create", "C3");
            MoveUnit(1, "Zeratul (Dark Templar)", CurrentPlayer, "Create", "C2");
            MoveUnit(1, "Zeratul (Dark Templar)", CurrentPlayer, "Create", "C1");
            RemoveUnitAt(All, "Men", "Create", CurrentPlayer);
            KillUnit("Protoss Dark Archon", CurrentPlayer);
            KillUnit("Zerg Scourge", CurrentPlayer);
            KillUnit("Zerg Lurker", CurrentPlayer);
            SetDeaths(P8, Add, 1, "Right Upper Level Door");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 1, "Right Pit Door");
            Deaths(P8, AtLeast, 1, "Right Upper Level Door");
            Deaths(P8, Exactly, 24, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C1", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C2", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C3", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C4", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C5", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C6", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C7", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C8", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            Order("Fenix (Zealot)", CurrentPlayer, "Anywhere", Patrol, "Last Boss 93");
            Wait(5000);
            KillUnit("Fenix (Zealot)", CurrentPlayer);
            KillUnit("Devouring One (Zergling)", CurrentPlayer);
            KillUnit("Hunter Killer (Hydralisk)", CurrentPlayer);
            SetDeaths(P8, SetTo, 0, "Left Pit Door");
            SetDeaths(P8, SetTo, 0, "Right Upper Level Door");
            SetDeaths(P8, SetTo, 2, "Right Pit Door");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 4, "Right Pit Door");
            Deaths(P8, AtLeast, 1, "Right Upper Level Door");
            Deaths(P8, Exactly, 12, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            CreateUnitWithProperties(1, "Terran Wraith", "C1", CurrentPlayer, {
                clocked = true,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(1, "Terran Wraith", CurrentPlayer, "C1", P9);
            CreateUnitWithProperties(1, "Terran Wraith", "C2", CurrentPlayer, {
                clocked = true,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(1, "Terran Wraith", CurrentPlayer, "C2", P10);
            CreateUnitWithProperties(1, "Terran Wraith", "C3", CurrentPlayer, {
                clocked = true,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(1, "Terran Wraith", CurrentPlayer, "C3", P11);
            CreateUnitWithProperties(1, "Terran Wraith", "C4", CurrentPlayer, {
                clocked = true,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(1, "Terran Wraith", CurrentPlayer, "C4", P12);
            CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C5", CurrentPlayer, {
                clocked = true,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(1, "Tom Kazansky (Wraith)", CurrentPlayer, "C5", P9);
            CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C6", CurrentPlayer, {
                clocked = true,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(1, "Tom Kazansky (Wraith)", CurrentPlayer, "C6", P10);
            CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C7", CurrentPlayer, {
                clocked = true,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(1, "Tom Kazansky (Wraith)", CurrentPlayer, "C7", P11);
            CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C8", CurrentPlayer, {
                clocked = true,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(1, "Tom Kazansky (Wraith)", CurrentPlayer, "C8", P12);
            CreateUnit(12, "Protoss Arbiter", "Location 122AA", P8);
            Order("Zeratul (Dark Templar)", CurrentPlayer, "Anywhere", Patrol, "Last Boss 93");
            Wait(5000);
            SetDeaths(P8, SetTo, 0, "Left Pit Door");
            SetDeaths(P8, SetTo, 0, "Right Upper Level Door");
            SetDeaths(P8, SetTo, 0, "Right Pit Door");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
        },
        actions = {
            PreserveTrigger();
            MoveLocation("C1", "Terran Wraith", P9, "Anywhere");
            MoveLocation("C2", "Terran Wraith", P10, "Anywhere");
            MoveLocation("C3", "Terran Wraith", P11, "Anywhere");
            MoveLocation("C4", "Terran Wraith", P12, "Anywhere");
            MoveLocation("C5", "Tom Kazansky (Wraith)", P9, "Anywhere");
            MoveLocation("C6", "Tom Kazansky (Wraith)", P10, "Anywhere");
            MoveLocation("C7", "Tom Kazansky (Wraith)", P11, "Anywhere");
            MoveLocation("C8", "Tom Kazansky (Wraith)", P12, "Anywhere");
            Order("Terran Wraith", P9, "Anywhere", Move, "C2");
            Order("Terran Wraith", P10, "Anywhere", Move, "C3");
            Order("Terran Wraith", P11, "Anywhere", Move, "C4");
            Order("Terran Wraith", P12, "Anywhere", Move, "C5");
            Order("Tom Kazansky (Wraith)", P9, "Anywhere", Move, "C6");
            Order("Tom Kazansky (Wraith)", P10, "Anywhere", Move, "C7");
            Order("Tom Kazansky (Wraith)", P11, "Anywhere", Move, "C8");
            Order("Tom Kazansky (Wraith)", P12, "Anywhere", Move, "C1");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
            Bring(AllPlayers, AtLeast, 4, "Tom Kazansky (Wraith)", "C1");
            Bring(AllPlayers, AtLeast, 4, "Terran Wraith", "C1");
        },
        actions = {
            PreserveTrigger();
            RemoveUnit("Terran Wraith", AllPlayers);
            RemoveUnit("Tom Kazansky (Wraith)", AllPlayers);
            RemoveUnit("Protoss Arbiter", P8);
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Bring(CurrentPlayer, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Deaths(P8, Exactly, 2, "Right Pit Door");
            Deaths(P8, Exactly, 0, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            Order("Terran Civilian", CurrentPlayer, "Anywhere", Move, "Last Boss 93");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Bring(CurrentPlayer, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Deaths(P8, Exactly, 2, "Right Pit Door");
            Deaths(P8, AtMost, 9, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            KillUnit("Devouring One (Zergling)", CurrentPlayer);
            KillUnit("Hunter Killer (Hydralisk)", CurrentPlayer);
            KillUnit("Torrasque (Ultralisk)", CurrentPlayer);
            CreateUnit(9, "Kakaru (Twilight)", "Last Boss 93", CurrentPlayer);
            KillUnit("Kakaru (Twilight)", CurrentPlayer);
            SetDeaths(P8, Add, 1, "Right Upper Level Door");
            Wait(1000);
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Bring(CurrentPlayer, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
            Deaths(P8, Exactly, 2, "Right Pit Door");
            Deaths(P8, AtMost, 9, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            ModifyUnitHitPoints(All, "Men", Foes, "Anywhere", 1);
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(P11, AtLeast, 1, "Artanis (Scout)");
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
        },
        actions = {
            PreserveTrigger();
            Order("Artanis (Scout)", P11, "Anywhere", Move, "Last Boss 93");
            SetInvincibility(Enable, "Artanis (Scout)", P11, "Anywhere");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Artanis (Scout)");
            Deaths(P8, Exactly, 3, "Right Pit Door");
        },
        actions = {
            PreserveTrigger();
            SetDeaths(P8, Add, 1, "Right Upper Level Door");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Artanis (Scout)");
            Deaths(CurrentPlayer, Exactly, 3, "Right Pit Door");
            Deaths(CurrentPlayer, Exactly, 110, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            Order("Artanis (Scout)", CurrentPlayer, "Anywhere", Patrol, "Last Boss 93");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Artanis (Scout)");
            Deaths(P8, Exactly, 3, "Right Pit Door");
            Deaths(P8, AtLeast, 140, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            SetDeaths(P8, SetTo, 0, "Right Upper Level Door");
            SetDeaths(P8, SetTo, 4, "Right Pit Door");
            SetDeaths(P8, SetTo, 0, "Left Pit Door");
            KillUnit("Artanis (Scout)", CurrentPlayer);
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(P11, AtMost, 149, "Artanis (Scout)");
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 0, "Left Pit Door");
            Deaths(P8, Exactly, 2, "Right Pit Door");
            Deaths(P8, AtLeast, 1, "Right Upper Level Door");
            Deaths(P8, AtLeast, 10, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            CreateUnitWithProperties(1, "Artanis (Scout)", "Last Boss 93", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 100,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            GiveUnits(All, "Artanis (Scout)", CurrentPlayer, "Anywhere", P11);
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(P11, AtLeast, 150, "Artanis (Scout)");
            Bring(CurrentPlayer, AtLeast, 1, "Terran Civilian", "Anywhere");
            Deaths(P8, Exactly, 0, "Left Pit Door");
            Deaths(P8, Exactly, 2, "Right Pit Door");
            Deaths(P8, AtLeast, 1, "Right Upper Level Door");
            Deaths(P8, AtLeast, 10, "Right Upper Level Door");
        },
        actions = {
            PreserveTrigger();
            SetDeaths(P8, SetTo, 3, "Right Pit Door");
            GiveUnits(All, "Artanis (Scout)", P11, "Anywhere", CurrentPlayer);
            RunAIScriptAt("Set Unit Order To: Junk Yard Dog", "Last Boss 93");
            SetInvincibility(Disable, "Artanis (Scout)", AllPlayers, "Last Boss 93");
        },
    }
    
    
    -- -----구분선-----
    -- 
    -- 
    -- 
    -- 
    -- 
    
    Trigger {
        players = {P8},
        conditions = {
            Always();
        },
        actions = {
            Comment("-----구분선-----\r\n\r\n\r\n\r\n\r\n");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
            Deaths(P8, Exactly, 0, "Left Pit Door");
        },
        actions = {
            CreateUnit(1, "Protoss Observer", "Create 1", CurrentPlayer);
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Anywhere", "Last Boss 93");
            RemoveUnit("Protoss Observer", CurrentPlayer);
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
            Deaths(P8, AtLeast, 1, "Left Pit Door");
            Deaths(P8, AtLeast, 11, "Right Upper Level Door");
        },
        actions = {
            CreateUnit(1, "Protoss Observer", "Create 1", CurrentPlayer);
            MoveUnit(1, "Protoss Observer", CurrentPlayer, "Anywhere", "Last Boss 93");
            RemoveUnit("Protoss Observer", CurrentPlayer);
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Gantrithor (Carrier)");
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
        },
        actions = {
            MoveLocation("Battlecruiser4", "Gantrithor (Carrier)", CurrentPlayer, "Anywhere");
            MoveLocation("Battlecruiser5give", "Gantrithor (Carrier)", CurrentPlayer, "Anywhere");
            CreateUnit(12, "Protoss Scout", "Battlecruiser4", CurrentPlayer);
            MoveUnit(All, "Protoss Scout", CurrentPlayer, "Anywhere", "Battlecruiser4");
            KillUnit("Protoss Scout", CurrentPlayer);
            GiveUnits(1, "Gantrithor (Carrier)", CurrentPlayer, "Battlecruiser5give", P11);
            MoveUnit(All, "Men", Foes, "Battlecruiser4", "Location 236AAA");
            MoveUnit(All, "Terran Bunker", Foes, "Battlecruiser4", "Location 236AAA");
            MoveUnit(All, "Terran Supply Depot", Foes, "Battlecruiser4", "Location 236AAA");
            MoveUnit(All, "Terran Missile Turret", Foes, "Battlecruiser4", "Location 236AAA");
            MoveUnit(All, "Terran Factory", Foes, "Battlecruiser4", "Location 236AAA");
            MoveUnit(All, "Terran Armory", Foes, "Battlecruiser4", "Location 236AAA");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
        },
        actions = {
            ModifyUnitHitPoints(All, "Any unit", Foes, "Location 236AAA", 0);
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, Exactly, 0, "Gantrithor (Carrier)");
            Command(P11, AtLeast, 1, "Gantrithor (Carrier)");
        },
        actions = {
            GiveUnits(All, "Gantrithor (Carrier)", P11, "Anywhere", CurrentPlayer);
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
        },
        actions = {
            PreserveTrigger();
            Order("Gantrithor (Carrier)", CurrentPlayer, "Anywhere", Move, "BattlecruiserHome 23");
            Order("Gantrithor (Carrier)", P11, "Anywhere", Move, "BattlecruiserHome 23");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Gantrithor (Carrier)", "BattlecruiserHome 23");
        },
        actions = {
            KillUnitAt(1, "Gantrithor (Carrier)", "BattlecruiserHome 23", CurrentPlayer);
            CreateUnit(8, "Rhynadon (Badlands)", "Last Boss 93", CurrentPlayer);
            KillUnit("Rhynadon (Badlands)", CurrentPlayer);
            CreateUnitWithProperties(6, "Devouring One (Zergling)", "Last Boss 93", CurrentPlayer, {
                clocked = false,
                burrowed = true,
                intransit = false,
                hallucinated = false,
                invincible = false,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(3, "Hunter Killer (Hydralisk)", "Last Boss 93", CurrentPlayer, {
                clocked = false,
                burrowed = true,
                intransit = false,
                hallucinated = false,
                invincible = false,
                hitpoint = 0,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnit(1, "Torrasque (Ultralisk)", "Last Boss 93", CurrentPlayer);
            Order("Men", CurrentPlayer, "Last Boss 93", Attack, "Anywhere");
            RunAIScriptAt("Set Unit Order To: Junk Yard Dog", "Last Boss 93");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Always();
        },
        actions = {
            SetSwitch("Switch 12", Set);
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Switch("Switch 12", Set);
        },
        actions = {
            CreateUnitWithProperties(40, "Terran Marine", "Location 236AAA", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 1,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            CreateUnitWithProperties(32, "Jim Raynor (Marine)", "Location 236AAA", CurrentPlayer, {
                clocked = false,
                burrowed = false,
                intransit = false,
                hallucinated = false,
                invincible = true,
                hitpoint = 1,
                shield = 100,
                energy = 100,
                resource = 0,
                hanger = 0,
            });
            RemoveUnitAt(40, "Terran Marine", "Location 236AAA", CurrentPlayer);
            SetAllianceStatus(P11, Ally);
            SetAllianceStatus(P10, Ally);
            SetAllianceStatus(P9, Ally);
            SetAllianceStatus(P12, Ally);
        },
    }
    
    
    -- -----구분선-----
    -- 
    -- 
    -- 
    -- 
    -- 
    
    Trigger {
        players = {P8},
        conditions = {
            Always();
        },
        actions = {
            Comment("-----구분선-----\r\n\r\n\r\n\r\n\r\n");
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Deaths(CurrentPlayer, Exactly, 300, "Left Upper Level Door");
        },
        actions = {
            MoveLocation("bossLocationboss 5", "Terran Civilian", CurrentPlayer, "Anywhere");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
            Bring(CurrentPlayer, Exactly, 0, "Terran Civilian", "bossLocationboss 5");
            Deaths(CurrentPlayer, AtLeast, 600, "Left Upper Level Door");
        },
        actions = {
            CreateUnit(1, "Edmund Duke (Siege Mode)", "Last Boss 93", CurrentPlayer);
            CreateUnit(1, "Edmund Duke (Siege Mode)", "bossLocationboss 5", CurrentPlayer);
            CreateUnit(9, "Tassadar/Zeratul (Archon)", "Last Boss 93", CurrentPlayer);
            KillUnit("Tassadar/Zeratul (Archon)", CurrentPlayer);
            MoveUnit(All, "Terran Civilian", CurrentPlayer, "Anywhere", "bossLocationboss 5");
            SetDeaths(CurrentPlayer, SetTo, 0, "Left Upper Level Door");
            MoveLocation("bossLocationboss 5", "Terran Civilian", CurrentPlayer, "Anywhere");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
            Bring(CurrentPlayer, Exactly, 1, "Terran Civilian", "bossLocationboss 5");
            Deaths(CurrentPlayer, AtLeast, 600, "Left Upper Level Door");
        },
        actions = {
            CreateUnit(1, "Edmund Duke (Siege Mode)", "Last Boss 93", CurrentPlayer);
            CreateUnit(1, "Edmund Duke (Siege Mode)", "BattlecruiserHome 23", CurrentPlayer);
            CreateUnit(9, "Tassadar/Zeratul (Archon)", "Last Boss 93", CurrentPlayer);
            KillUnit("Tassadar/Zeratul (Archon)", CurrentPlayer);
            MoveUnit(All, "Terran Civilian", CurrentPlayer, "Anywhere", "BattlecruiserHome 23");
            SetDeaths(CurrentPlayer, SetTo, 0, "Left Upper Level Door");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Terran Civilian");
        },
        actions = {
            SetDeaths(CurrentPlayer, Add, 1, "Left Upper Level Door");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Switch("Switch 12", Set);
            Command(CurrentPlayer, AtLeast, 1, "Protoss Arbiter");
        },
        actions = {
            MoveUnit(All, "Protoss Arbiter", CurrentPlayer, "Anywhere", "Location 122AA");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Switch("Switch 12", Set);
            Command(CurrentPlayer, AtLeast, 1, "Protoss Arbiter");
        },
        actions = {
            PreserveTrigger();
            RunAIScriptAt("Recall Here", "C1");
            RunAIScriptAt("Recall Here", "C2");
            RunAIScriptAt("Recall Here", "C3");
            RunAIScriptAt("Recall Here", "C4");
            RunAIScriptAt("Recall Here", "C5");
            RunAIScriptAt("Recall Here", "C6");
            RunAIScriptAt("Recall Here", "C7");
            RunAIScriptAt("Recall Here", "C8");
        },
    }
    
    
    Trigger {
        players = {Force1},
        conditions = {
            Command(P8, AtLeast, 1, "Terran Civilian");
            Deaths(P8, Exactly, 3, "Right Pit Door");
            Deaths(P8, AtLeast, 138, "Right Upper Level Door");
        },
        actions = {
            RunAIScript("Turn OFF Shared Vision for Player 8");
        },
    }
    
    
    Trigger {
        players = {Force1},
        conditions = {
            Command(P8, AtLeast, 1, "Terran Civilian");
        },
        actions = {
            SetDeaths(P10, Add, 1, "Terran Civilian");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {Force1},
        conditions = {
            Deaths(P10, AtLeast, 2700, "Terran Civilian");
        },
        actions = {
            PlayWAV("staredit\\wav\\Lumina.wav");
            PlayWAV("staredit\\wav\\Lumina.wav");
            PlayWAV("staredit\\wav\\Lumina.wav");
            PlayWAV("staredit\\wav\\Lumina.wav");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Deaths(P10, AtLeast, 2700, "Terran Civilian");
        },
        actions = {
            SetDeaths(P10, SetTo, 0, "Terran Civilian");
            PreserveTrigger();
        },
    }
    
    
    Trigger { -- EUD터보 SetTo 1짜리 넣으면 일반 터보트리거와 똑같은 효과를 발휘함. 아마도...? 이놈의 위치는 어디든 상관없성
        players = {P8},
        actions = {
            SetMemory(0x6509A0, SetTo, 0x00000001);
            PreserveTrigger();
            Comment("EUD터보 SetTo 1짜리 넣으면 일반 터보트리거와 똑같은 효과를 발휘함. 아마도...? 이놈의 위치는 어디든 상관없성");
        },
    }
    
    
    Trigger {
        players = {Force1},
        actions = {
            RunAIScript("Turn ON Shared Vision for Player 8");
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {P8},
        conditions = {
            Never();
            Memory(0xEDAC6530, AtLeast, 0x6ACEBAEA);
            Memory(0x34972300, AtLeast, 0xABDDB7EA);
        },
        actions = {
            SetDeaths(P1, SetTo, 837853517, "Terran Marine");
            SetDeaths(P1, SetTo, 1695775756, "Terran Marine");
        },
    }
    
    
    
end