

-- 용자의땅 오픈소스에서 가져옴
-- from MSF Braver's Land
-- Thanks to DemonLanterns, -Men-
function Install_DemBoss()-- This text is generated by TrigEditPlus

	local Wr_T = CreateCCode()

	local DM_T0C = CreateCCode()
	local DM_T1C = CreateCCode()
	local DM_T2C = CreateCCode()
	local DM_T3C = CreateCCode()
	local DM_T4C = CreateCCode()
	local DM_T5C = CreateCCode()
	local DM_T6C = CreateCCode()
	local DM_T7C = CreateCCode()
	local DM_T8C = CreateCCode()
	DM_T0 = "\n\n\n\n\n\n\n\n\x13\x04『 \x06이제 그분이 오실 것이다. \x04』\n\n"
	DM_T1 = "\n\n\n\n\n\n\n\n\x13\x04『 \x06이 층의 지배자이자 ... 절대자께서 ...\x04 』\n\n"
	DM_T2 = "\n\n\n\n\n\n\n\n\x13\x04『 \x06재앙을 알리는 일식이, 시작되었다. \x04』\n\n"
	DM_T3 = "\n\n\n\n\n\n\n\n\x13\x04『 \x06돌이키기에는 이제 늦었다. \x04』\n\n"
	DM_T4 = "\n\n\n\n\n\n\n\n\x13\x04『 \x06...라는 마음이 싹트는 것을 깨달았을 때 \x04』\n\n"
	DM_T5 = "\n\n\n\n\n\n\n\n\x13\x04『 \x06마음속에서는 선과 악이 깨어난다! \x04』\n\n"
	DM_T6 = "\n\n\n\n\n\n\n\n\x13\x04『 \x06당신들의 마음은 어느 쪽인가? \x04』\n\n"
	DM_T7 = "\n\n\n\n\n\n\n\n\x13\x04『 \x06\x17D\x04emonic\x08Emperor \x04: \x06죽음을 준비하라. \x04』\n\n"
	local ViOff = CreateCCode()
	local ViON = CreateCCode()


	CIf(FP,{CDeaths(FP,AtLeast,1,StoryT4)})
	if TestMode == 1 then
		CAdd(FP,_Ccode("X",StoryT4),1000)
	else
		CAdd(FP,_Ccode("X",StoryT4),Dt)
	end
	
	StoryPrint(6000*(0),{
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		DisplayTextX(DM_T0,4);
	},DM_T0C,nil,StoryT4) 
	StoryPrint(6000*(1),{
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		DisplayTextX(DM_T1,4);
	},DM_T1C,nil,StoryT4) 
	StoryPrint(6000*(2),{
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		DisplayTextX(DM_T2,4);
	},DM_T2C,{SetCDeaths(FP,Add,1,ViOff)},StoryT4) 
	StoryPrint(6000*(3),{
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		DisplayTextX(DM_T3,4);
	},DM_T3C,nil,StoryT4) 
	StoryPrint(6000*(4),{
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		DisplayTextX(DM_T4,4);
	},DM_T4C,nil,StoryT4) 
	StoryPrint(6000*(5),{
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		DisplayTextX(DM_T5,4);
	},DM_T5C,nil,StoryT4) 
	StoryPrint(6000*(6),{
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		PlayWAVX("staredit\\wav\\button3.wav");
		DisplayTextX(DM_T6,4);
	},DM_T6C,nil,StoryT4) 
	StoryPrint(42*1000,{
		TalkingPortrait(68, 6100);
		PlayWAVX("staredit\\wav\\statyoudie.wav");
		PlayWAVX("staredit\\wav\\statyoudie.wav");
		DisplayTextX(DM_T7,4);
	},DM_T7C,nil,StoryT4) 

		CIf(FP,{Memory(0x628438,AtLeast,1),CDeaths(FP,AtLeast,42*1000,StoryT4),CDeaths(FP,AtMost,0,DM_T8C),})
		f_Read(FP,0x628438,nil,Nextptrs,0xFFFFFF)
		CDoActions(FP,{
			KillUnitAt(All,"Men","Center",Force1),
			CreateUnit(1,"Terran Civilian","Last Boss 93",FP),
			TSetMemory(_Add(Nextptrs,2),SetTo,6500*256),
			SetCDeaths(FP,SetTo,1,DM_T8C),
			SetCDeaths(FP,Add,1,ViON),
			SetCVar(FP,ReserveBGM[2],SetTo,Akasha),
		})
		TriggerX(FP,{CDeaths(FP,Exactly,0,isSingle)},{RotatePlayer({
			MinimapPing("Last Boss 93"),
			CenterView("Last Boss 93"),
		},HumanPlayers,FP)},{Preserved})
		CIfEnd()

	CIfEnd()
	TriggerX(FP,{CDeaths(FP,AtLeast,1,ViOff)},{RotatePlayer({
		RunAIScript("Turn OFF Shared Vision for Player 1"),
		RunAIScript("Turn OFF Shared Vision for Player 2"),
		RunAIScript("Turn OFF Shared Vision for Player 3"),
		RunAIScript("Turn OFF Shared Vision for Player 4"),
		RunAIScript("Turn OFF Shared Vision for Player 5"),
		RunAIScript("Turn OFF Shared Vision for Player 6"),
		RunAIScript("Turn OFF Shared Vision for Player 7"),
	},MapPlayers,FP)},{Preserved})
	TriggerX(FP,{CDeaths(FP,AtLeast,1,ViON)},{RotatePlayer({
		RunAIScript("Turn ON Shared Vision for Player 1"),
		RunAIScript("Turn ON Shared Vision for Player 2"),
		RunAIScript("Turn ON Shared Vision for Player 3"),
		RunAIScript("Turn ON Shared Vision for Player 4"),
		RunAIScript("Turn ON Shared Vision for Player 5"),
		RunAIScript("Turn ON Shared Vision for Player 6"),
		RunAIScript("Turn ON Shared Vision for Player 7"),
	},MapPlayers,FP),SetCDeaths(FP,SetTo,0,ViOff)},{Preserved})
	CIfX(FP,Bring(FP,AtLeast,1,"Terran Civilian",64),SetCVar(FP,VResetSw3[2],SetTo,0))
	CIf(FP,{NTCond()},{SetMemory(0x6509B0,SetTo,FP)})--다크아칸 에너지 스크립트 복구
	DoActions(FP,{
		SetAllianceStatus(P11, Ally);
		SetAllianceStatus(P10, Ally);
		SetAllianceStatus(P9, Ally);
		SetAllianceStatus(P12, Ally);
	})
	CMov(FP,VO(41),LevelT2) -- Diff
	Trigger2(FP,{Void(4,AtMost,0)},{
		SetVoid(4,SetTo,1),
	},{Preserved})

	DoActions2(FP,MoveMarineArr2)

	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			MoveLocation("Last Boss 93", "Terran Civilian", P8, "Anywhere");
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
		},
		actions = {
			PreserveTrigger();
			Order("Terran Civilian", P8, "Anywhere", Move, "Last Boss 93");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(AllPlayers, Exactly, 0, "Terran Wraith", "Anywhere");
			Bring(AllPlayers, Exactly, 0, "Tom Kazansky (Wraith)", "Anywhere");
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 0); 
			Void(1, Exactly, 0);
		},
		actions = {
			PreserveTrigger();
			SetVoid(0, SetTo, 1); 
			SetVoid(1, SetTo, 1);
			SetVoid(2, SetTo, 1);
			MoveLocation("C1", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C2", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C3", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C4", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C5", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C6", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C7", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C8", "Terran Civilian", P8, "Anywhere");
			MoveLocation("BattlecruiserHome 23", "Terran Civilian", P8, "Anywhere");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 4); 
			Void(1, Exactly, 0);
		},
		actions = {
			PreserveTrigger();
			SetVoid(0, SetTo, 4); 
			SetVoid(1, SetTo, 1);
			SetVoid(2, SetTo, 1);
			MoveLocation("C1", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C2", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C3", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C4", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C5", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C6", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C7", "Terran Civilian", P8, "Anywhere");
			MoveLocation("C8", "Terran Civilian", P8, "Anywhere");
			MoveLocation("BattlecruiserHome 23", "Terran Civilian", P8, "Anywhere");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 1); 
			Void(2, AtLeast, 1);
			Void(2, AtMost, 23);
		},
		actions = {
			PreserveTrigger();
			CreateUnit(1, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C1");
			MoveLocation("C1", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(2, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C2");
			MoveLocation("C2", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(3, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C3");
			MoveLocation("C3", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(4, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C4");
			MoveLocation("C4", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(5, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C5");
			MoveLocation("C5", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(6, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C6");
			MoveLocation("C6", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(7, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C7");
			MoveLocation("C7", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(8, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C8");
			MoveLocation("C8", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 4); 
			Void(2, AtLeast, 1);
			Void(2, AtMost, 15);
		},
		actions = {
			PreserveTrigger();
			CreateUnit(1, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C1");
			MoveLocation("C1", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(2, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C2");
			MoveLocation("C2", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(3, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C3");
			MoveLocation("C3", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(4, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C4");
			MoveLocation("C4", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(5, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C5");
			MoveLocation("C5", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(6, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C6");
			MoveLocation("C6", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(7, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C7");
			MoveLocation("C7", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
			CreateUnit(8, "Zerg Devourer", "Create 1", P8);
			CreateUnit(1, "Protoss Arbiter", "Create 2", P8);
			MoveUnit(All, "Men", P8, "Create", "C8");
			MoveLocation("C8", "Protoss Arbiter", P8, "Anywhere");
			RemoveUnit("Protoss Arbiter", P8);
			RemoveUnit("Zerg Devourer", P8);
		},
	}

	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 1); 
			Void(2, AtLeast, 1);
			Void(2, AtMost, 23);
		},
		actions = {
			PreserveTrigger();
			CreateUnit(8, "Protoss Dark Archon", "Create 1", P8);
			CreateUnit(8, "Kakaru (Twilight)", "Create 1", P8);
			CreateUnitWithProperties(8, "Protoss High Templar", "Create 1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(8, "Fenix (Zealot)", "Create 1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = false,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C1");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C2");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C3");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C4");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C5");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C6");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C7");
			MoveUnit(1, "Kakaru (Twilight)", P8, "Create", "C8");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C1");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C2");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C3");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C4");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C5");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C6");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C7");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C8");
			MoveUnit(1, "Protoss High Templar", P8, "Create", "C1");
			MoveUnit(1, "Protoss High Templar", P8, "Create", "C2");
			MoveUnit(1, "Protoss High Templar", P8, "Create", "C3");
			MoveUnit(1, "Protoss High Templar", P8, "Create", "C4");
			MoveUnit(1, "Protoss High Templar", P8, "Create", "C5");
			MoveUnit(1, "Protoss High Templar", P8, "Create", "C6");
			MoveUnit(1, "Protoss High Templar", P8, "Create", "C7");
			MoveUnit(1, "Protoss High Templar", P8, "Create", "C8");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C8");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C7");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C6");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C5");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C4");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C3");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C2");
			MoveUnit(1, "Fenix (Zealot)", P8, "Create", "C1");
			killUnitAt(All,"Men","C8",Force1);
			killUnitAt(All,"Men","C7",Force1);
			killUnitAt(All,"Men","C6",Force1);
			killUnitAt(All,"Men","C5",Force1);
			killUnitAt(All,"Men","C4",Force1);
			killUnitAt(All,"Men","C3",Force1);
			killUnitAt(All,"Men","C2",Force1);
			killUnitAt(All,"Men","C1",Force1);
			RemoveUnitAt(All, "Men", "Create", P8);
			KillUnit("Protoss Dark Archon", P8);
			KillUnit("Kakaru (Twilight)", P8);
			KillUnit("Protoss High Templar", P8);
			SetVoid(2, Add, 1);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 4); 
			Void(2, AtLeast, 1);
			Void(2, AtMost, 15);
		},
		actions = {
			PreserveTrigger();
			CreateUnit(8, "Protoss Dark Archon", "Create 1", P8);
			CreateUnit(8, "Zerg Scourge", "Create 1", P8);
			CreateUnitWithProperties(8, "Zerg Lurker", "Create 1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(8, "Zeratul (Dark Templar)", "Create 1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = false,
				hitpoint = 10,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C1");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C2");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C3");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C4");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C5");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C6");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C7");
			MoveUnit(1, "Zerg Scourge", P8, "Create", "C8");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C1");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C2");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C3");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C4");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C5");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C6");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C7");
			MoveUnit(1, "Protoss Dark Archon", P8, "Create", "C8");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C1");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C2");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C3");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C4");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C5");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C6");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C7");
			MoveUnit(1, "Zerg Lurker", P8, "Create", "C8");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C8");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C7");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C6");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C5");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C4");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C3");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C2");
			MoveUnit(1, "Zeratul (Dark Templar)", P8, "Create", "C1");
			RemoveUnitAt(All, "Men", "Create", P8);
			KillUnit("Protoss Dark Archon", P8);
			KillUnit("Zerg Scourge", P8);
			KillUnit("Zerg Lurker", P8);
			SetVoid(2, Add, 1);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 1); 
			Void(2, AtLeast, 1);
			Void(2, Exactly, 24);
			Void(5,AtMost,0);
		},
		actions = {
			PreserveTrigger();
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C1", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C2", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C3", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C4", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C5", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C6", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C7", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(1, "Gantrithor (Carrier)", "C8", P8, {
				clocked = false,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			Order("Fenix (Zealot)", P8, "Anywhere", Patrol, "Last Boss 93");
			SetVoid(5,SetTo,1);
			SetVoid(2,Add,1);
		},
	}
	CIf(FP,{Void(5,AtLeast,1)})
		CAdd(FP,_Ccode("X",WaitT),Dt_NT)
		TriggerX(FP,{CDeaths(FP,AtLeast,5000,WaitT)},{
			KillUnit("Fenix (Zealot)", P8);
		KillUnit(88, P8);
		KillUnit("Devouring One (Zergling)", P8);
		KillUnit("Hunter Killer (Hydralisk)", P8);
		SetVoid(1, SetTo, 0);
		SetVoid(2, SetTo, 0);
		SetVoid(0, SetTo, 2);
		SetVoid(5, SetTo, 0);
		SetCDeaths(FP,SetTo,0,WaitT)
	 },{Preserved})
	CIfEnd()
	f_ArrReset({
	Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
	Void(0, Exactly, 4); 
	Void(2, AtLeast, 1);
	Void(2, Exactly, 16);
	Void(6,AtMost,0);})

	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(0, Exactly, 4); 
			Void(2, AtLeast, 1);
			Void(2, Exactly, 16);
			Void(6,AtMost,0);
		},
		actions = {
			PreserveTrigger();
			CreateUnitWithProperties(1, "Terran Wraith", "C1", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Terran Wraith", P8, "C1", P9);
			CreateUnitWithProperties(1, "Terran Wraith", "C2", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Terran Wraith", P8, "C2", P10);
			CreateUnitWithProperties(1, "Terran Wraith", "C3", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Terran Wraith", P8, "C3", P11);
			CreateUnitWithProperties(1, "Terran Wraith", "C4", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Terran Wraith", P8, "C4", P12);
			CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C5", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Tom Kazansky (Wraith)", P8, "C5", P9);
			CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C6", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Tom Kazansky (Wraith)", P8, "C6", P10);
			CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C7", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Tom Kazansky (Wraith)", P8, "C7", P11);
			CreateUnitWithProperties(1, "Tom Kazansky (Wraith)", "C8", P8, {
				clocked = true,
				burrowed = false,
				intransit = false,
				hallucinated = false,
				invincible = true,
				hitpoint = 100,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			GiveUnits(1, "Tom Kazansky (Wraith)", P8, "C8", P12);
			Order("Zeratul (Dark Templar)", P8, "Anywhere", Patrol, "Last Boss 93");
			SetVoid(6,SetTo,1);
		},
	}
	local WaitT2 = CreateCCode()
	CIf(FP,{Void(6,AtLeast,1)})
	CAdd(FP,_Ccode("X",WaitT2),Dt_NT)
	TriggerX(FP,{CDeaths(FP,AtLeast,5000,WaitT2)},{
	SetVoid(1, SetTo, 0);
	SetVoid(2, SetTo, 0);
	SetVoid(0, SetTo, 0);
	SetVoid(6, SetTo, 0);
	SetCDeaths(FP,SetTo,0,WaitT2)
	},{Preserved})
	CIfEnd()

	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
		},
		actions = {
			PreserveTrigger();
			MoveLocation("C1", "Terran Wraith", P9, "Anywhere");
			MoveLocation("C2", "Terran Wraith", P10, "Anywhere");
			MoveLocation("C3", "Terran Wraith", P11, "Anywhere");
			MoveLocation("C4", "Terran Wraith", P12, "Anywhere");
			MoveLocation("C5", "Tom Kazansky (Wraith)", P9, "Anywhere");
			MoveLocation("C6", "Tom Kazansky (Wraith)", P10, "Anywhere");
			MoveLocation("C7", "Tom Kazansky (Wraith)", P11, "Anywhere");
			MoveLocation("C8", "Tom Kazansky (Wraith)", P12, "Anywhere");
			Order("Terran Wraith", P9, "Anywhere", Move, "C2");
			Order("Terran Wraith", P10, "Anywhere", Move, "C3");
			Order("Terran Wraith", P11, "Anywhere", Move, "C4");
			Order("Terran Wraith", P12, "Anywhere", Move, "C5");
			Order("Tom Kazansky (Wraith)", P9, "Anywhere", Move, "C6");
			Order("Tom Kazansky (Wraith)", P10, "Anywhere", Move, "C7");
			Order("Tom Kazansky (Wraith)", P11, "Anywhere", Move, "C8");
			Order("Tom Kazansky (Wraith)", P12, "Anywhere", Move, "C1");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere");
			Bring(AllPlayers, AtLeast, 4, "Tom Kazansky (Wraith)", "C1");
			Bring(AllPlayers, AtLeast, 4, "Terran Wraith", "C1");
		},
		actions = {
			PreserveTrigger();
			RemoveUnit("Terran Wraith", AllPlayers);
			RemoveUnit("Tom Kazansky (Wraith)", AllPlayers);
			RemoveUnit("Protoss Arbiter", P8);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Void(0, Exactly, 2); 
			Void(2, Exactly, 0);
		},
		actions = {
			PreserveTrigger();
			Order("Terran Civilian", P8, "Anywhere", Move, "Last Boss 93");
		},
	}
	
	CAdd(FP,VO(7),Dt_NT)
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Void(0, Exactly, 2); 
			Void(2, AtMost, 9);
			Void(7,AtLeast,1000)

		},
		actions = {
			PreserveTrigger();
			KillUnit("Devouring One (Zergling)", P8);
			KillUnit("Hunter Killer (Hydralisk)", P8);
			KillUnit("Torrasque (Ultralisk)", P8);
			CreateUnit(9,91, "Last Boss 93", P8);
			ModifyUnitHitPoints(All, "Men", Force1, "Anywhere", 1);
			KillUnit(91, P8);
			KillUnitAt(20,75,64,FP);
			SetVoid(2, Add, 1);
			SetVoid(7, SetTo, 0);
			
		},
	}
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Bring(P8, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Bring(P11, Exactly, 0, "Gantrithor (Carrier)", "Anywhere");
			Void(0, Exactly, 2); 
			Void(2, AtMost, 9);
			Void(41, AtLeast, 3);
		},
		actions = {
			PreserveTrigger();
			ModifyUnitHitPoints(All, "Men", Force1, "Anywhere", 1);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P11, AtLeast, 1, "Identity JinjinZZara Noodles");
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			PreserveTrigger();
			Order("Identity JinjinZZara Noodles", P11, "Anywhere", Move, "Last Boss 93");
			SetInvincibility(Enable, "Identity JinjinZZara Noodles", P11, "Anywhere");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Identity JinjinZZara Noodles");
			Void(0, Exactly, 3); 
		},
		actions = {
			PreserveTrigger();
			SetVoid(2, Add, 1);
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Identity JinjinZZara Noodles");
			Void(0, Exactly, 3); 
			Void(2, Exactly, 110);
		},
		actions = {
			PreserveTrigger();
			Order("Identity JinjinZZara Noodles", P8, "Anywhere", Patrol, "Last Boss 93");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Identity JinjinZZara Noodles");
			Void(0, Exactly, 3); 
			Void(2, AtLeast, 140);
		},
		actions = {
			PreserveTrigger();
			SetVoid(2, SetTo, 0);
			SetVoid(0, SetTo, 4); 
			SetVoid(1, SetTo, 0);
			KillUnit("Identity JinjinZZara Noodles", P8);
		},
	}
	CIf(FP,{
		Command(P11, AtMost, 149, "Identity JinjinZZara Noodles");
		Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
		Void(1, Exactly, 0);
		Void(0, Exactly, 2); 
		Void(2, AtLeast, 1);
		Void(2, AtLeast, 10);
		Memory(0x628438,AtLeast,1)
	})

	f_CRandNum(1600,200,{Void(41,Exactly,3)})
	f_CRandNum(2400,200,{Void(41,AtLeast,4)})
	f_CRandNum(1000,200,{Void(41,AtMost,2)})
	local Seed = TempRandRet
		f_Read(FP,0x628438,nil,Sh_Para,0xFFFFFF)
		CDoActions(FP,{
				KillUnit(103,FP),
				TSetMemory(0x6CA1F4, SetTo, Seed),
				TSetMemoryX(0x6C9DF4, SetTo, _Mul(Seed,_Mov(65536)),0xFFFF0000),
				CreateUnitWithProperties(1, 60, "Last Boss 93", P8, {invincible = true}),
				TSetDeathsX(_Add(Sh_Para,72),SetTo,0xFF*256,0,0xFF00),
				TSetDeathsX(_Add(Sh_Para,55),SetTo,0x200104,0,0x300104),
				TSetDeaths(_Add(Sh_Para,57),SetTo,0,0),
				GiveUnits(All,60,P8,64,P11),
			})
	CIfEnd()
	
local Angle = CreateVar(FP)
local PosX = CreateVar(FP)
local PosY = CreateVar(FP)
local PosX2 = CreateVar(FP)
local PosY2 = CreateVar(FP)
CIf(FP,{Command(P11, AtLeast, 150, "Identity JinjinZZara Noodles"),
Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
Void(1, Exactly, 0);
Void(0, Exactly, 2); 
Void(2, AtLeast, 1);
Void(2, AtLeast, 10);})
GetLocCenter("Last Boss 93",PosX2,PosY2)
CWhile(FP,CVar(FP,Angle[2],AtMost,359))
f_Lengthdir(FP,250,Angle,PosX,PosY)
CAdd(FP,PosX,PosX2)
CAdd(FP,PosY,PosY2)
f_Recall(nil,PosX,PosY)
CAdd(FP,Angle,5)
CWhileEnd()
CMov(FP,Angle,0)

CIfEnd()

	Trigger {
		players = {P8},
		conditions = {
			Command(P11, AtLeast, 150, "Identity JinjinZZara Noodles");
			Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
			Void(1, Exactly, 0);
			Void(0, Exactly, 2); 
			Void(2, AtLeast, 1);
			Void(2, AtLeast, 10);
		},
		actions = {
			PreserveTrigger();
			SetVoid(0, SetTo, 3); 
			GiveUnits(All, "Identity JinjinZZara Noodles", P11, "Anywhere", P8);
			RunAIScriptAt("Set Unit Order To: Junk Yard Dog", 64);
		},
	}
	
	
	-- -----구분선-----
	-- 
	-- 
	-- 
	-- 
	-- 
	
	Trigger {
		players = {P8},
		conditions = {
			Always();
		},
		actions = {
			Comment("-----구분선-----\r\n\r\n\r\n\r\n\r\n");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
			Void(1, Exactly, 0);
		},
		actions = {
			CreateUnit(1, "Kakaru (Twilight)", "Create 1", P8);
			MoveUnit(1, "Kakaru (Twilight)", P8, "Anywhere", "Last Boss 93");
			RemoveUnit("Kakaru (Twilight)", P8);
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
			Void(1, AtLeast, 1);
			Void(2, AtLeast, 11);
		},
		actions = {
			CreateUnit(1, "Kakaru (Twilight)", "Create 1", P8);
			MoveUnit(1, "Kakaru (Twilight)", P8, "Anywhere", "Last Boss 93");
			RemoveUnit("Kakaru (Twilight)", P8);
			PreserveTrigger();
		},
	}

	TriggerX(FP,{Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
	Void(0, Exactly, 1); 
	Void(2, Exactly, 23);},{SetCVar(FP,CurArr[2],SetTo,0)},{Preserved})
	local WrPos = CreateVar(FP)
	local WhileLim = CreateCCode()
	local Wr_Sum = def_sIndex()
	CIf(FP,{
		Command(P8, AtLeast, 1, "Gantrithor (Carrier)")
	})	
		CJumpEnd(FP,Wr_Sum)
		NIf(FP,{TMemory(_Add(XY_ArrHeader,CurArr),AtLeast,1),CDeaths(FP,AtMost,7,WhileLim)},SetCDeaths(FP,Add,1,WhileLim))
			f_Read(FP,_Add(XY_ArrHeader,CurArr),CPos)
			Convert_CPosXY()
			Simple_SetLocX(FP,0,CPosX,CPosY,CPosX,CPosY,{CreateUnitWithProperties(1,"Zerg Lurker",1,FP,{burrowed = true}),CreateUnit(1,"Kakaru (Twilight)",1,FP),KillUnit("Kakaru (Twilight)",FP)})
			CAdd(FP,CurArr,1)
			CJump(FP,Wr_Sum)
		NIfEnd()
		DoActionsX(FP,SetCDeaths(FP,SetTo,0,WhileLim))
	CIfEnd()

	CWhile(FP,{
		Command(P8, AtLeast, 1, "Gantrithor (Carrier)");
		Command(P8, AtLeast, 1, "Terran Civilian");
	})
	DoActions(FP,{
		MoveLocation("Battlecruiser4", "Gantrithor (Carrier)", P8, "Anywhere");
		MoveLocation("Battlecruiser5give", "Gantrithor (Carrier)", P8, "Anywhere");
	})
	local SY = CreateVar(FP)
	local SZ = CreateVar(FP)
	local SW = CreateVar(FP)
	function S2_CAfunc2()
		local PlayerID = CAPlotPlayerID
		local CA = CAPlotDataArr
		local CB = CAPlotCreateArr
		CA_Rotate3D(SY,SZ,SW) -- XY : SY, YZ : SZ, ZX : SW 만큼 회전
	end
	function CA_Recall()
		local PlayerID = CAPlotPlayerID
		local CA = CAPlotDataArr
		local CB = CAPlotCreateArr
		f_Recall(nil,V(CA[8]),V(CA[9]))
	end
	DoActionsX(FP,{SetCVar("X",SY[2],Add,1),SetCVar("X",SZ[2],Add,1),SetCVar("X",SW[2],Add,1)})
	SetLocCenter2("Battlecruiser4")
	CAPlot({CSMakePolygon(4,150,90,PlotSizeCalc(4,1),PlotSizeCalc(4,0))},FP,nilunit,"Location 1",nil,1,32,{1,0,0,0,20,0},"S2_CAfunc2",FP,nil,nil,1,"CA_Recall")
	Trigger {
		players = {P8},
		conditions = {
		},
		actions = {
			KillUnit("Protoss Scout", P8);
			GiveUnits(1, "Gantrithor (Carrier)", P8, "Battlecruiser5give", P11);
			PreserveTrigger();
		},
	}
	Trigger {
		players = {P8},
		conditions = {
			Void(41,AtLeast,2)
		},
		actions = {
			KillUnitAt(All,"Men","Battlecruiser4",Force1);
			KillUnitAt(All,"Terran Bunker","Battlecruiser4",Force1);
			KillUnitAt(All,"Terran Missile Turret","Battlecruiser4",Force1);
			PreserveTrigger();
		},
	}
	CWhileEnd()
	
	
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, Exactly, 0, "Gantrithor (Carrier)");
			Command(P11, AtLeast, 1, "Gantrithor (Carrier)");
		},
		actions = {
			GiveUnits(All, "Gantrithor (Carrier)", P11, "Anywhere", P8);
			PreserveTrigger();
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			PreserveTrigger();
			Order("Gantrithor (Carrier)", P8, "Anywhere", Move, "BattlecruiserHome 23");
			Order("Gantrithor (Carrier)", P11, "Anywhere", Move, "BattlecruiserHome 23");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Bring(P8, AtLeast, 1, "Gantrithor (Carrier)", "BattlecruiserHome 23");
		},
		actions = {
			KillUnitAt(1, "Gantrithor (Carrier)", "BattlecruiserHome 23", P8);
			CreateUnit(8, "Rhynadon (Badlands)", "Last Boss 93", P8);
			KillUnit("Rhynadon (Badlands)", P8);
			CreateUnitWithProperties(6, "Devouring One (Zergling)", "Last Boss 93", P8, {
				clocked = false,
				burrowed = true,
				intransit = false,
				hallucinated = false,
				invincible = false,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnitWithProperties(3, "Hunter Killer (Hydralisk)", "Last Boss 93", P8, {
				clocked = false,
				burrowed = true,
				intransit = false,
				hallucinated = false,
				invincible = false,
				hitpoint = 0,
				shield = 100,
				energy = 100,
				resource = 0,
				hanger = 0,
			});
			CreateUnit(1, "Torrasque (Ultralisk)", "Last Boss 93", P8);
			Order("Men", P8, "Last Boss 93", Attack, "Anywhere");
			RunAIScriptAt("Set Unit Order To: Junk Yard Dog", "Last Boss 93");
			PreserveTrigger();
		},
	}
	
	
	
	
	
	-- -----구분선-----
	-- 
	-- 
	-- 
	-- 
	-- 
	
	Trigger {
		players = {P8},
		conditions = {
			Always();
		},
		actions = {
			Comment("-----구분선-----\r\n\r\n\r\n\r\n\r\n");
		},
	}
	
	
	Trigger {
		players = {P8},
		conditions = {
			Void(3, Exactly, 300);
		},
		actions = {
			MoveLocation("bossLocationboss 5", "Terran Civilian", P8, "Anywhere");
			PreserveTrigger();
		},
	}
	CIf(FP,{
		Command(P8, AtLeast, 1, "Terran Civilian");
		Bring(P8, Exactly, 0, "Terran Civilian", "bossLocationboss 5");
		Void(3, AtLeast, 600);

	})
	DoActions(FP,CreateUnit(1,"Edmund Duke (Siege Mode)","Last Boss 93",FP))
	DoActions(FP,CreateUnit(1,"Edmund Duke (Siege Mode)","bossLocationboss 5",FP))
	CSPlot(CSMakePolygon(8,128,90,9,1),FP,"Edmund Duke (Siege Mode)","Last Boss 93",nil,1,32,FP,{Void(41,AtLeast,4)},nil,1)
	CSPlot(CSMakePolygon(8,128,90,9,1),FP,"Edmund Duke (Siege Mode)","bossLocationboss 5",nil,1,32,FP,{Void(41,AtLeast,4)},nil,1)
	Trigger {
		players = {P8},
		actions = {
			CreateUnit(9, "Tassadar/Zeratul (Archon)", "Last Boss 93", P8);
			KillUnit("Tassadar/Zeratul (Archon)", P8);
			MoveUnit(All, "Terran Civilian", P8, "Anywhere", "bossLocationboss 5");
			SetVoid(3, SetTo, 0);
			MoveLocation("bossLocationboss 5", "Terran Civilian", P8, "Anywhere");
			PreserveTrigger();
		},
	}
	CIfEnd()
	
	
	CIf(FP,{
		Command(P8, AtLeast, 1, "Terran Civilian");
		Bring(P8, Exactly, 1, "Terran Civilian", "bossLocationboss 5");
		Void(3, AtLeast, 600);})
		DoActions(FP,CreateUnit(1,"Edmund Duke (Siege Mode)","Last Boss 93",FP))
		DoActions(FP,CreateUnit(1,"Edmund Duke (Siege Mode)","BattlecruiserHome 23",FP))
	CSPlot(CSMakePolygon(8,128,90,9,1),FP,"Edmund Duke (Siege Mode)","Last Boss 93",nil,1,32,FP,{Void(41,AtLeast,4)},nil,1)
	CSPlot(CSMakePolygon(8,128,90,9,1),FP,"Edmund Duke (Siege Mode)","BattlecruiserHome 23",nil,1,32,FP,{Void(41,AtLeast,4)},nil,1)
	Trigger {
		players = {P8},
		conditions = {
		},
		actions = {
			CreateUnit(9, "Tassadar/Zeratul (Archon)", "Last Boss 93", P8);
			KillUnit("Tassadar/Zeratul (Archon)", P8);
			MoveUnit(All, "Terran Civilian", P8, "Anywhere", "BattlecruiserHome 23");
			SetVoid(3, SetTo, 0);
			PreserveTrigger();
		},
	}
	CIfEnd()
	
	Trigger {
		players = {P8},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
		},
		actions = {
			SetVoid(3, Add, 1);
			PreserveTrigger();
		},
	}
	
	GetLocCenter("Last Boss 93",CX,CY)
	f_Recall({
		Command(P11, AtMost, 149, "Identity JinjinZZara Noodles");
		Bring(P8, AtLeast, 1, "Terran Civilian", "Anywhere");
		Void(1, Exactly, 0);
		Void(0, Exactly, 2); 
		Void(2, AtLeast, 1);
		Void(2, AtLeast, 10);
	},CX,CY)

	-- ArraySetCallSpace

	CIf(FP,Bring(AllPlayers, AtLeast, 1, "Tom Kazansky (Wraith)", "Anywhere"))
	DoActionsX(FP,{SetCDeaths(FP,Add,2,Wr_T)})
	GetLocCenter("C1",CX,CY)
	f_Recall(nil,CX,CY)
	CallTriggerX(FP,WrPosSave,{CDeaths(FP,AtLeast,10,Wr_T)})
	GetLocCenter("C2",CX,CY)
	f_Recall(nil,CX,CY)
	CallTriggerX(FP,WrPosSave,{CDeaths(FP,AtLeast,10,Wr_T)})
	GetLocCenter("C3",CX,CY)
	f_Recall(nil,CX,CY)
	CallTriggerX(FP,WrPosSave,{CDeaths(FP,AtLeast,10,Wr_T)})
	GetLocCenter("C4",CX,CY)
	f_Recall(nil,CX,CY)
	CallTriggerX(FP,WrPosSave,{CDeaths(FP,AtLeast,10,Wr_T)})
	GetLocCenter("C5",CX,CY)
	f_Recall(nil,CX,CY)
	CallTriggerX(FP,WrPosSave,{CDeaths(FP,AtLeast,10,Wr_T)})
	GetLocCenter("C6",CX,CY)
	f_Recall(nil,CX,CY)
	CallTriggerX(FP,WrPosSave,{CDeaths(FP,AtLeast,10,Wr_T)})
	GetLocCenter("C7",CX,CY)
	f_Recall(nil,CX,CY)
	CallTriggerX(FP,WrPosSave,{CDeaths(FP,AtLeast,10,Wr_T)})
	GetLocCenter("C8",CX,CY)
	f_Recall(nil,CX,CY)
	CallTriggerX(FP,WrPosSave,{CDeaths(FP,AtLeast,10,Wr_T)})
	TriggerX(FP,{CDeaths(FP,AtLeast,10,Wr_T)},{SetCDeaths(FP,SetTo,0,Wr_T)},{Preserved})
	CIfEnd()
	Trigger {
		players = {Force1},
		conditions = {
			Command(P8, AtLeast, 1, "Terran Civilian");
			Void(0, Exactly, 3); 
			Void(2, AtLeast, 138);
		},
		actions = {
			RunAIScript("Turn OFF Shared Vision for Player 8");
		},
	}
	DoActions2(FP,OWTable)
	
	
	DoActions(FP,{RotatePlayer({RunAIScript(P8VON)},MapPlayers,FP)})
	CIfEnd()
	CElseIfX({CVar(FP,VResetSw3[2],Exactly,0),Bring(FP,AtMost,0,"Terran Civilian",64)},SetCVar(FP,VResetSw3[2],SetTo,1))
		CallTrigger(FP,Call_VoidReset)
		DoActionsX(FP,{KillUnit("Any unit",FP),KillUnit("Any unit",P9),KillUnit("Any unit",P10),KillUnit("Any unit",P11),KillUnit("Any unit",P12),SetCDeaths(FP,Add,1,DemClear)})
		DoActionsX(FP,{
			SetCDeaths(FP,SetTo,0,DM_T0C),
			SetCDeaths(FP,SetTo,0,DM_T1C),
			SetCDeaths(FP,SetTo,0,DM_T2C),
			SetCDeaths(FP,SetTo,0,DM_T3C),
			SetCDeaths(FP,SetTo,0,DM_T4C),
			SetCDeaths(FP,SetTo,0,DM_T5C),
			SetCDeaths(FP,SetTo,0,DM_T6C),
			SetCDeaths(FP,SetTo,0,DM_T7C),
			SetCDeaths(FP,SetTo,0,DM_T8C),
			SetCDeaths(FP,SetTo,0,ViOff),
			SetCDeaths(FP,SetTo,0,ViON),
			SetCDeaths(FP,SetTo,0,StoryT4),
			SetMemory(0x6CA1F4, SetTo, 1707),
			SetMemoryX(0x6C9DF4, SetTo, 67*65536,0xFFFF0000),
		})
		f_ArrReset()
	CIfXEnd()

	
end