
DoActions(P8,SetResources(Force1,Add,-1,Gas),1)
DoActions(Force1,SetDeaths(CurrentPlayer,SetTo,1,227),1)
TestSet(2)
VerText = "\x04Ver. Test"
FP = P8
EUDTurbo(FP) -- µ≤≈Õ∫∏
SetForces({P1,P2,P3,P4,P5,P6,P7},{P8},{},{},{P1,P2,P3,P4,P5,P6,P7,P8})
SetFixedPlayer(FP)
Enable_PlayerCheck()
Trigger2(FP,{PlayerCheck(0,0),PlayerCheck(1,0),PlayerCheck(2,0),PlayerCheck(3,0),PlayerCheck(4,0),PlayerCheck(5,0),PlayerCheck(6,0)},{Defeat()})
Enable_HideErrorMessage(FP)
StartCtrig()
	CIf(AllPlayers,ElapsedTime(AtLeast,3))
		init_func = def_sIndex()
		CJump(AllPlayers,init_func)
			Include_CtrigPlib(360,"Switch 100",1)
			Objects()
			HPoints()
			Var_init()
			Install_CallTriggers()
		CJumpEnd(AllPlayers,init_func)
		DoPlayerCheck()
		NoAirCollisionX(FP)
		onInit_EUD() -- onPluginStart
		BGMManager()
		Gun_System()
		Install_RandPlaceHero()
		SetWave()
		OPText() -- Opening Text
		GameOver()
		Overflow_HP_System(FP,B1_H,B1_K)
		IBGM_EPDX(FP,6,Dt)
		UnitReadX(FP,AllPlayers,229,64,count)
		ObDisplay()
		LevelUp()
		SetRecoverCp()
		RecoverCp(AllPlayers)
		CIf(FP,ElapsedTime(AtLeast,4))
			onInit_EUD2()
			MapPreserves()
			OPTrig()
			PlayerInterface()
			Print_TotalScore()
			LeaderBoardTFunc()
			Test_LV1()
			Test_LV2()
		CIfEnd()
		Install_AllObject()
	CIfEnd()
EndCtrig()
ErrorCheck()
SetCallErrorCheck()
