function DataArr()
	
	PVWArr = {
		{iv.Money,ct.Money,"Money"},
		{iv.Money2,ct.Money2,"Money2"},
		{iv.IncomeMax,ct.IncomeMax,"IncomeMax"},
		{iv.Income,ct.Income,"Income"},
		{iv.BuildMul1,ct.BuildMul1,"BuildMul1"},
		{iv.BuildMul2,ct.BuildMul2,"BuildMul2"},
		{iv.TotalEPer,ct.TotalEPer,"TotalEPer"},
		{iv.TotalEPer2,ct.TotalEPer2,"TotalEPer2"},
		{iv.TotalEPer3,ct.TotalEPer3,"TotalEPer3"},
		{iv.TotalEPer4,ct.TotalEPer4,"TotalEPer4"},
		{iv.ScoutDmg,ct.ScoutDmg,"ScoutDmg"},
		{iv.ScTimer,ct.ScTimer,"ScTimer"},
		{iv.PTimeV,ct.PTimeV,"PTimeV"},
		{iv.General_Upgrade,ct.General_Upgrade,"General_Upgrade"},
		{iv.ResetStat,ct.ResetStat,"ResetStat"},
		{iv.NextOre,ct.NextOre,"NextOre"},
		{iv.NextGas,ct.NextGas,"NextGas"},
		{iv.NextOreMul,ct.NextOreMul,"NextOreMul"},
		{iv.NextGasMul,ct.NextGasMul,"NextGasMul"},
		{iv.SellTicket,ct.SellTicket,"SellTicket"},
		{iv.PBossLV,ct.PBossLV,"PBossLV"},
		{iv.PBossDPS,ct.PBossDPS,"PBossDPS"},
		{iv.TotalPBossDPS,ct.TotalPBossDPS,"TotalPBossDPS"},
		{iv.Stat_EXPIncome,ct.Stat_EXPIncome,"Stat_EXPIncome"},
		{iv.PLevel,ct.PLevel,"PLevel"},
		{iv.StatP,ct.StatP,"StatP"},
		{iv.Stat_ScDmg,ct.Stat_ScDmg,"Stat_ScDmg"},
		{iv.Stat_AddSc,ct.Stat_AddSc,"Stat_AddSc"},
		{iv.Stat_TotalEPer,ct.Stat_TotalEPer,"Stat_TotalEPer"},
		{iv.Stat_TotalEPerEx,ct.Stat_TotalEPerEx,"Stat_TotalEPerEx"},
		{iv.Stat_TotalEPer2,ct.Stat_TotalEPer2,"Stat_TotalEPer2"},
		{iv.Stat_TotalEPer3,ct.Stat_TotalEPer3,"Stat_TotalEPer3"},
		{iv.Stat_TotalEPer4,ct.Stat_TotalEPer4,"Stat_TotalEPer4"},
		{iv.Stat_BreakShield,ct.Stat_BreakShield,"Stat_BreakShield"},
		{iv.Stat_Upgrade,ct.Stat_Upgrade,"Stat_Upgrade"},
		{iv.Credit,ct.Credit,"Credit"},
		{iv.PEXP,ct.PEXP,"PEXP"},
		{iv.TotalExp,ct.TotalExp,"TotalExp"},
		{iv.CurEXP,ct.CurEXP,"CurEXP"},
		{iv.PStatVer,ct.PStatVer,"PStatVer"},
		{iv.PlayTime2,ct.PlayTime2,"PlayTime2"},
		{iv.PlayTime,ct.PlayTime,"PlayTime"},
		{iv.CreditAddSC,ct.CreditAddSC,"CreditAddSC"},
		{iv.LV5Cool,ct.LV5Cool,"LV5Cool"},
		{iv.B_PCredit,ct.B_PCredit,"B_PCredit"},
		{iv.B_PTicket,ct.B_PTicket,"B_PTicket"},
		{iv.BanFlag,ct.BanFlag,"BanFlag"},
		{iv.BanFlag2,ct.BanFlag2,"BanFlag2"},
		{iv.BanFlag3,ct.BanFlag3,"BanFlag3"},
		{iv.BanFlag4,ct.BanFlag4,"BanFlag4"},
		{iv.TempO,ct.TempO,"TempO"},
		{iv.TempG,ct.TempG,"TempG"},
		{iv.TempX,ct.TempX,"TempX"},
		{iv.TimeAttackScore,ct.TimeAttackScore,"TimeAttackScore"},
		{iv.TimeAttackScore2,ct.TimeAttackScore2,"TimeAttackScore2"},
		{iv.PUnitLevel,ct.PUnitLevel,"PUnitLevel"},
		{iv.PUnitClass,ct.PUnitClass,"PUnitClass"},
		{iv.CurPUnitCool,ct.CurPUnitCool,"CurPUnitCool"},
		{iv.VaccItem,ct.VaccItem,"VaccItem"},
		{iv.CS_Cooldown,ct.CS_Cooldown,"CS_Cooldown"},
		{iv.CS_Atk,ct.CS_Atk,"CS_Atk"},
		{iv.CS_EXP,ct.CS_EXP,"CS_EXP"},
		{iv.CS_TotalEPer,ct.CS_TotalEPer,"CS_TotalEPer"},
		{iv.CS_TotalEper4,ct.CS_TotalEper4,"CS_TotalEper4"},
		{iv.CS_DPSLV,ct.CS_DPSLV,"CS_DPSLV"},
		{iv.CS_EXPData,ct.CS_EXPData,"CS_EXPData"},
		{iv.CS_TEPerData,ct.CS_TEPerData,"CS_TEPerData"},
		{iv.CS_TEPer4Data,ct.CS_TEPer4Data,"CS_TEPer4Data"},
		{iv.RandomSeed1,ct.RandomSeed1,"RandomSeed1"},
		{iv.RandomSeed2,ct.RandomSeed2,"RandomSeed2"},
		{iv.RandomSeed3,ct.RandomSeed3,"RandomSeed3"},
		{iv.RandomSeed4,ct.RandomSeed4,"RandomSeed4"},
		{iv.RandomSeed5,ct.RandomSeed5,"RandomSeed5"},
		{iv.RandomSeed6,ct.RandomSeed6,"RandomSeed6"},
		{iv.RandomSeed7,ct.RandomSeed7,"RandomSeed7"},
		{iv.RandomSeed8,ct.RandomSeed8,"RandomSeed8"},
		{iv.RandomSeed9,ct.RandomSeed9,"RandomSeed9"},
		{iv.RandomSeed10,ct.RandomSeed10,"RandomSeed10"},
		{iv.PUnitEnchCool,ct.PUnitEnchCool,"PUnitEnchCool"},
		
		
		
	}
	

	

	VWArr = {
		{iv.PCheckV,ctg.PCheckV,"PCheckV"},
		{iv.B_IncomeMax,ctg.B_IncomeMax,"B_IncomeMax"},
		{iv.B_TotalEPer,ctg.B_TotalEPer,"B_TotalEPer"},
		{iv.B_TotalEPer2,ctg.B_TotalEPer2,"B_TotalEPer2"},
		{iv.B_TotalEPer3,ctg.B_TotalEPer3,"B_TotalEPer3"},
		{iv.B_Stat_EXPIncome,ctg.B_Stat_EXPIncome,"B_Stat_EXPIncome"},
		{iv.B_Stat_Upgrade,ctg.B_Stat_Upgrade,"B_Stat_Upgrade"},
		{iv.B_Credit,ctg.B_Credit,"B_Credit"},
		{iv.B_Ticket,ctg.B_Ticket,"B_Ticket"},
		{iv.BossLV,ctg.BossLV,"BossLV"},
		{iv.CUnitT,ctg.CUnitT,"CUnitT"}
	}
	SCA_DataArr = {
		{iv.BanFlag4,95},
		{iv.BanFlag3,96},
		{iv.BanFlag2,97},
		{iv.BanFlag,98},
		{iv.PLevel,101},
		{iv.StatP,102},
		{iv.Stat_ScDmg,103},
		{iv.Stat_TotalEPer,104},
		{iv.Stat_TotalEPer2,105},
		{iv.Stat_TotalEPer3,106},
		{iv.Stat_Upgrade,107},
		{iv.Credit,108},
		{iv.PEXP,110},
		{iv.TotalExp,112},
		{iv.CurEXP,114},
		{iv.Stat_AddSc,116},
		{iv.PStatVer,117},
		{iv.PlayTime,118},
		{iv.PlayTime2,119},
		{iv.CreditAddSC,120},
		{iv.LV5Cool,121},
		{iv.Stat_TotalEPer4,122},
		{iv.Stat_BreakShield,123},
		{iv.Stat_TotalEPerEx,124},
		{iv.TimeAttackScore,125},
		{iv.PUnitLevel,126},
		{iv.PUnitClass,127},
		{iv.VaccItem,128},
		{iv.CS_Cooldown,129},
		{iv.CS_Atk,130},
		{iv.CS_EXP,131},
		{iv.CS_TotalEPer,132},
		{iv.CS_TotalEper4,133},
		{iv.CS_DPSLV,134},
		{iv.RandomSeed1,135},
		{iv.RandomSeed2,136},
		{iv.RandomSeed3,137},
		{iv.RandomSeed4,138},
		{iv.RandomSeed5,139},
		{iv.RandomSeed6,140},
		{iv.RandomSeed7,141},
		{iv.RandomSeed8,142},
		{iv.RandomSeed9,143},
		{iv.RandomSeed10,144},
	}
	
	BPArr = {iv.BanFlag,iv.BanFlag2,iv.BanFlag3,iv.BanFlag4}

	iv.Stat_TotalEPerEx2,ct.Stat_TotalEPerEx2 = CreateDataPV("Stat_TotalEPerEx2",145)
	iv.Stat_TotalEPerEx3,ct.Stat_TotalEPerEx3 = CreateDataPV("Stat_TotalEPerEx3",146)
end